language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get install gfortran
install:
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install Cython
  - python setup.py build_ext --inplace
script:
  - nosetests -s pymc/tests/